language: python
python:
- '3.6'
- 3.6-dev
install:
- pip install -r requirements.txt
script:
- echo "OK"
deploy:
  provider: script
  script:
  - "./deploy.sh"
  on:
    branch: master    
env:
  global:  
  - secure: "QiWXo6SRRTbNUhxMTpPCBBOnqJjbmkHmSXhRPWI5ebRwez7Og4hrmyfu7vhW4enze2tfKjtvTkX3ENSmO6zLINVFb268QI6vcJmithSUaQTkcPXQaoQEqKJ4T0X6uiKejkhc8GPtov4n1dqySihaV+cvS2gAQf4a3xre9ZTpZaYv6pa5z3XPgKMg5jbKL9c/X07aDv+k8eZdxJERTj4I67bF3GlMbraPUAXCuoHlRwInNA3V67E2Uct6JCZrLkkXGoJUsd3zoaFd7jOtevgGoD9tkmanH67FzR/LwTTuAXhUQ9xerSAs6yhr756v2Xzmn+d1vKr6/X2rpjafqYmL11V9e0YN5OjDtFud0xHRmRXPGZBnWXgOJq7eNoiKRmVrdDsxIRUal06QP8aBLXEWbsjsGkLA85eqn6AjZaOLrMpbcO5SPIoYvc/HM5XWBEFCDLYc7YwsMUXQ533Ra0ptKutDfHumpwRtQ1Z4hOej7SM1IcIcyqRXXjWNLp56LbdIFtYxa7/E4fl3VJB3lQ8p1uzKxQMJ35I8EBjziwZsUcojXBWyfj47YTJjoiZOjxcrAFvHN+j9zxmT9NU599OYxFow7J3OrU8G709WxT9pbgWImYZzUFWwqgmnohAxgcUJZOO203st2dLQmdx4skLMAPIpk5V/Jf351SgRQPwPJF4="
  - secure: "nN/1QE1gEHzG7BQbRhRVhoFj56hz8bpqGjMyttLlFT/7rN6XhEnsmM2Z9vwdrzwwNh5CodYCa2IeGpxruBUbfgIkYHbq7tnVdS98aPbPpQYRe36lzM7j48zQVpVX3cslBlBeQCyla6+0wKrjQ/pIJoDdIi7d2ZuNopF/dpg28THPEenIJ1BHMTZ0Ztm8adnppyx+mqtcjRlO6r1QoLFL47zmW507eSTvVZ+0LxJX28Khkr9OMPbFcEqt2Kr+i2hMTDjoZApRx4ltuQ4fxnS81m9c4drcf5heNKlB9m17PLMyQ5/xYeOS/tYH8dlPTMY7AtFF+kPKw0OtlGWXkPaHYycy53JMx9VdrpjO0ExX7+ydTHjm7QK8+vBEEtyL94X8ykT2QheTmh4fv9rBrxpH67SkB3GHPlE6Kp01BCePWRWTnYSTVGph7TeF+7Fc2sn4G3cLN/SdwJHZ8OWT414Zl4rUwglg/Uu/A1x90cbeAG24CPb+wciqEnRyapmeS5OFOzeJSDtOLEL41fgYNFxayj1t/GRFp4GtpiLOBNMvWRSRJhSqTbQzuSAR5OIs9R1Rh3rErQ1dQ20UHuGp3014Rbpmo6zzWoW2rKTTLeVCdBWlN+QroVR1/CcMNSYGiYoZDwnoMGoiKLEA/qzDKHEqby2VjQp0CxqOa3kwAqy1z9c="

