language: python
python:
- '3.6'
- 3.6-dev
install:
- pip install -r requirements.txt
script:
- echo "OK"
deploy:
  provider: script
  script:
  - "./deploy.sh"
  on:
    branch: master
env:
  global:
  - secure: toPiUn9FVyoFaF6wlZn6ZF2KaHCaUmqnCsMtic1xcCs/nUF0iv19q4XIveAlAzgeRtsmFd7oxhp1LBhWjW15SBe2WwvBsyEgGsC6zPb3aNh6mk1L1wU2Gup/256wvuxkMJSAsglA/Tf5sSTfoGhyUj80pp6Hq1wvpdwV6AYHvrYsgMy8WST2p9tJ5zFj+3D4oWBgI9jIVqZV+Z2IZnjRpwZESEnINU5b95j5d7S4dpeFDM/rCOn5HsdDOcZSoVT6DyXLMchCi5zTQ8pxwksEbS+TvAdWPLsS6X32k9Fb6DNHZbSMUBqjQe65xrDFSr9sraLZbRVMhJ/PFquysQf+K0g89jupJK/NKXZ+1JWI51cbhz9igtWkeqqaAc30nzzzWyjONrZWAiOpFO9di5Hb40bvEommOM4q61dxRHgOtvWOiODFTwgxSUL2kExOH+6xCLRJu/33boqTeNJShYsUn1vA3Ob2xScJJyzSUAIQRO+44CRVKZXpxrDwFh6TY35zejfnmQuJYUdRsM2KoSoTHRwfolNdDbcF4TzW1iyiIKjMln9cjpnx0LaTENDK9bThJ7xcWrlyL55bs7tuQoSKggBAfauOi0Bd+/Mt1ktnpqxKl374ZTHXHVw6kZr+5aaW/R2PfdD0cL2ZFfoW29Pzg22gu8Bf+HW636yYrN3vSmA=
  - secure: DxFy2CzyHx00B48xq+FIcU5dHSxs92VmDnNmZ27x8OyzvOXZSv/gpOfE1HI8rFZp+IkE9XQSlc2cPBCN7QInb7LQoBDtVYAgL1oFoQa4NRRkd9IP4MMo6xCdhVgDR/X6H2eHCmW+JXJU1iOzyVZLD/+DusansL3PCPhkBkIGL4wgeXA6f2TnVDzQtgGAVD5l5z8SzjtTGF1Ti5/Wjugaa5CTHLBz1CAbe143AuLsLCH14Oqn1JsHIFJvtQDE1gzEyN/xy44Sr4lAAVt1rtFDa/0mjSoKET5iSpAq5OtoOJJxfaU+Om/uot3FggTzmCYrVFw9kMbr+2SoI3vy54TM9NNwODVojFp2lLlU6Y0QL8HCrP7SiISgHGlnCyLPr/5O7SaxwXPhhxL83PQWEU4ZtPaHHWgZrROj5pp3OvMmfdvps0VXgXoPRL0r1iVsR81eIISMgALLP93KbIJc4eW+RM8Zw66xTKWADa6VEvJd1Z1WpBuX67zI3pL6WmCFZ1zic4r06gXgd4uEq4FwVvMshYzsvti++MDsMQa8jFiEjnKgF2n/63jNqjXEtu276kN95q5UK3X3iHA4D5fXGgXIhIKiFnVxd5FSnJvYg9M14eDUrUxmOd0G8s0ttDHmynBKmYm8Ji5kL3+1+QvgrqfaMDkfv/XRKOcX8ngWWF2FbKs=
