language: python
python:
- '3.6'
- 3.6-dev
install:
- pip install -r requirements.txt
script:
- echo "OK"
deploy:
  provider: script
  script:
  - "./deploy.sh"
  on:
    branch: master    
env:
  global:
  - secure: j53e+I6+d7TrgMWdq2jX9HCQSmRiTfwT5/x6SWLgcvP5GOVL5fO9IjNFf+CloDzkqWNSr8pM6EjLjXc9Yfl+MnNTAUjJRNf6d7acUR8Zt/ds0DI+Vviyci+FbRIdCnRnPPnAMdgrszF8t1GZ5tcCPxqsDFwE3uAFSzfI04trSlhEuMY6gav5nm5hjkiS+qSo4fGmLoisez+UQ3v8nWYZ+OUo/2vW9wRzpB4CiGP6nTI9g/E1l3oYKVhaqfYUGhTLb6TcL5TasTyHMPD3/Ghbf7/yxFMXtyTmgDEfmToRYd7p5Xa8quY6my4p/CV9qjaf1cLUKgHqzj3u6uXilRrGxtHxJr8V3hjz+LoZnXUeHJiRtMr1IJC/yDPYeZzkmerj+NQZcOZIiULToDGIgPfB0qCL4DbkeS6Ol1HbYbbPZLaO38ES12AM2oob0W7LXjingt4n+CqvMTNM7h+hzsCRmBfXhzzr7Y2sqEtEZlm9jtGbzAE8uh4trg8p1BIzEv1QheGRfogKC+NEc4LhHUBpX2yWu8kwtUjSIWEl3pUJtg4nOd41/GlebwWaOZXRcN/Nkb2oQLalEJTJjYXJcPZs254SjCaxKhEHu1J9Onxcis8uGdsUmxfAyDhJRXNW/txUgAKGEx8EiVIvte1hMAV7zArlrw+6/Z4zHxsrqGueuSk=
  - secure: h1T0iFG+Q/mW4Njnz4EPBSsIxm38CY1/UU7ki22ohSuALpczAsJwZh1SdRW2gSfU7AyGsVyqStg/9IDSv/1/0v1v002H9Icx/rf0b1bf0QAwxvjrYyEz+AH/bXa2nHXjx9YqsNAx+lUprptAmHdzo2dk1kxgrI4Wl16luLMoYQFmOpVKu5LUkyIeI9I4wypxMGXAGXpa7Ndc5SYWMvT2AzZ3xxnzfQvtCpaCxTnEC9OFa/CX3iXUP3r+/R3L72+NW3c7fiGY4l8riIAkYdFrcUGSQ/ssZpS2gLJm6EYytqmsi6jRUs/nm5HNJwP9s21drBeTDutHNrSzvQYMMBdPgo4lxDUf1brXop0sbIRHFbeaDEv/eWPhDQHaognod2htk7hVmoQtihuY30xGjva16ij3oGFY8a/NHXwgw6pfBHNmWd8drhNaQO7GTcXtX8a2abuh84WzwtZukOcxeOoISgMofG+YMuBcsEqYylxGzwShJT47QylxUokTNaI/Giv/4PsRZ1/nbHnkz9h+AjZ52FtAlW9Yl+jU+xsgmsK1Ai69vqqFAG5dv6RWRMh4dC9GEa9uj+SWXjvNszk9i5iceCvQQFD3MsckrZXRBrGqqRDpf8+nRQOQRwFnhgpIY1M0GAD3C87dhaSvGAY6VABHHumUMs2+uT7qyq2n/9XDC+Q=

